import sendgrid
from sendgrid.helpers.mail import Mail
import os
from dotenv import load_dotenv

load_dotenv()

def send_meeting_summary(to_email: str, meeting_title: str, insights: dict):
    sg = sendgrid.SendGridAPIClient(api_key=os.getenv("SENDGRID_API_KEY"))
    
    # Build email body
    decisions = "\n".join([f"• {d}" for d in insights.get("decisions", [])]) or "None recorded"
    action_items = "\n".join([f"• {a.get('description', a.get('task', 'Unknown task'))} (Assignee: {a.get('assignee') or a.get('assignee_email') or 'Unknown'})" for a in insights.get("action_items", [])]) or "None recorded"
    open_questions = "\n".join([f"• {q}" for q in insights.get("open_questions", [])]) or "None recorded"
    topics = ", ".join(insights.get("topics", [])) or "None recorded"
    summary = insights.get("summary", "No summary available")

    html_content = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: #4f46e5; padding: 24px; border-radius: 8px 8px 0 0;">
            <h1 style="color: white; margin: 0; font-size: 22px;">🧠 MeetMind Summary</h1>
            <p style="color: #c7d2fe; margin: 4px 0 0;">{meeting_title}</p>
        </div>
        
        <div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 8px 8px;">
            <h2 style="color: #1f2937; font-size: 16px;">📋 Meeting Overview</h2>
            <p style="color: #6b7280;">{summary}</p>
            
            <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
            
            <h2 style="color: #1f2937; font-size: 16px;">✅ Key Decisions</h2>
            <pre style="color: #374151; font-family: Arial; white-space: pre-wrap;">{decisions}</pre>
            
            <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
            
            <h2 style="color: #1f2937; font-size: 16px;">📌 Action Items</h2>
            <pre style="color: #374151; font-family: Arial; white-space: pre-wrap;">{action_items}</pre>
            
            <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
            
            <h2 style="color: #1f2937; font-size: 16px;">❓ Open Questions</h2>
            <pre style="color: #374151; font-family: Arial; white-space: pre-wrap;">{open_questions}</pre>
            
            <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
            
            <h2 style="color: #1f2937; font-size: 16px;">🏷️ Topics Discussed</h2>
            <p style="color: #374151;">{topics}</p>
            
            <div style="background: #f3f4f6; padding: 16px; border-radius: 8px; margin-top: 24px;">
                <p style="color: #6b7280; font-size: 13px; margin: 0;">
                    This summary was automatically generated by MeetingAI.
                </p>
            </div>
        </div>
    </div>
    """

    message = Mail(
       from_email=os.getenv("SENDER_EMAIL", "meetingai@yourdomain.com"),
        to_emails=to_email,
        subject=f"Meeting Summary: {meeting_title}",
        html_content=html_content
    )

    try:
        response = sg.send(message)
        return {"success": True, "status_code": response.status_code}
    except Exception as e:
        return {"success": False, "error": str(e)}