import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env'))

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
SENDER_EMAIL = os.getenv("SENDER_EMAIL")

def send_meeting_summary(to_emails: list, meeting_title: str, insights: dict):
    decisions = "\n".join([f"• {d}" for d in insights.get("decisions", [])])
    action_items = "\n".join([f"• {a['task']} — Assignee: {a.get('assignee', 'unknown')}" for a in insights.get("action_items", [])])
    open_questions = "\n".join([f"• {q}" for q in insights.get("open_questions", [])])
    topics = "\n".join([f"• {t}" for t in insights.get("topics", [])])

    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px;">
        <h2 style="color: #2c3e50;">Meeting Summary: {meeting_title}</h2>
        
        <h3 style="color: #27ae60;">📋 Summary</h3>
        <p>{insights.get("summary", "No summary available")}</p>

        <h3 style="color: #2980b9;">✅ Key Decisions</h3>
        <pre style="background: #f8f9fa; padding: 10px; border-radius: 5px;">{decisions or "No decisions recorded"}</pre>

        <h3 style="color: #e74c3c;">📌 Action Items</h3>
        <pre style="background: #f8f9fa; padding: 10px; border-radius: 5px;">{action_items or "No action items recorded"}</pre>

        <h3 style="color: #f39c12;">❓ Open Questions</h3>
        <pre style="background: #f8f9fa; padding: 10px; border-radius: 5px;">{open_questions or "No open questions recorded"}</pre>

        <h3 style="color: #8e44ad;">🗂️ Topics Discussed</h3>
        <pre style="background: #f8f9fa; padding: 10px; border-radius: 5px;">{topics or "No topics recorded"}</pre>

        <hr>
        <p style="color: #95a5a6; font-size: 12px;">This summary was automatically generated by Meeting Assistant.</p>
    </body>
    </html>
    """

    message = Mail(
        from_email=SENDER_EMAIL,
        to_emails=to_emails,
        subject=f"Meeting Summary: {meeting_title}",
        html_content=html_content
    )

    try:
        sg = SendGridAPIClient(SENDGRID_API_KEY)
        response = sg.send(message)
        return {"status": "sent", "code": response.status_code}
    except Exception as e:
        return {"status": "failed", "error": str(e)}